#!/usr/bin/env bash
set -Eeuo pipefail

PATTERN=${1:-"apps/*/ap-stage/version.yaml"}
SVC_NAME_PATH_DEPTH=${2:-2}

idx=0
for name in $(git log -1 --name-only --pretty='')
do
    if [[ "$name" == $PATTERN ]]
    then
        services[$idx]="$(echo -n "$name" | cut -d / -f "$SVC_NAME_PATH_DEPTH")"
        idx=$((idx+1))
    fi
done

printf -v joined '%s, ' "${services[@]}"
echo "${joined%, }"
