name: "Change Notification"
"on":
  workflow_call:
    inputs:
      pattern:
        required: true
        type: string
      env_name:
        required: true
        type: string

jobs:
  determine-change:
    name: "Determine Change"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Discover Changed Services
        run: |
          echo "CHANGED_SERVICES=$(scripts/changed-services "${{ inputs.pattern }}")" >> $GITHUB_ENV
      - name: Explain Changes
        run: |
          echo The following apps or services have been updated in the "${{ inputs.env_name}}" environment: "${{ env.CHANGED_SERVICES }}"
          echo See "${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}" for the commit that triggered this notification
  send-notification:
    name: "Send Notification"
    runs-on: ubuntu-latest
    needs:
      - determine-change
    steps:
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.23
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.GITOPS_PROMOTIONS_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text" : "The following apps or services have been updated in the \"${{ inputs.env_name}}\" environment: ${{ env.CHANGED_SERVICES }}. See "${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}" for the commit that triggered this notification.",
            }
