name: Change Notification
"on":
  push:
    branches:
      - "main"
    paths:
      - 'apps/*/ap-stage/version.yaml'
env:
  PATTERN: 'apps/*/ap-stage/version.yaml'
  ENV_NAME: 'Stage'
jobs:
  announce-change:
    name: "Announce Change"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: List changes
        run: |
          set -e
          echo "Promotion to $ENV_NAME has occurred"
          for name in $(git log -1 --name-only --pretty='')
          do
              if [[ "$name" == $PATTERN ]]
              then
                  echo "Changed: $name"
              fi
          done
