name: Change Notification (Production)
"on":
  push:
    branches:
      - "main"
    paths:
      - 'apps/*/ap-prod-*/version.yaml'

jobs:
  announce-change:
    name: "Announce Change"
    uses: ./.github/workflows/changes-notify.yaml
    with:
      pattern: "apps/*/ap-prod-*/version.yaml"
      env_name: "Production"
