name: Change Notification (Production)
"on":
  push:
    branches:
      - "main"
    paths:
      - 'apps/*/ap-prod-*/version.yaml'
env:
  PATTERN: 'apps/*/ap-prod-*/version.yaml'
  ENV_NAME: 'Production'
jobs:
  announce-change:
    uses: ./.github/workflows/change-notify.yaml
    with:
      pattern: "${{ env.PATTERN }}"
      env_name: "${{ env.ENV_NAME }}"
