name: Change Notification (Stage)
"on":
  push:
    branches:
      - "main"
    paths:
      - 'apps/*/ap-stage/version.yaml'

jobs:
  announce-change:
    name: "Announce Change"
    uses: ./.github/workflows/changes-notify.yaml
    with:
      pattern: "apps/*/ap-stage/version.yaml"
      env_name: "Stage"
