on:
  workflow_dispatch:
    inputs:
      a:
        description: 'A'
        required: false
        default: 'a'
        type: string
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
